/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/draft/pool/abilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** AddAbility */
        post: operations["ApiDraftPoolAbilitiesAddAbility"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/draft/pool/heroes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** AddHero */
        post: operations["ApiDraftPoolHeroesAddHero"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GetDraft */
        get: operations["ApiDraftGetDraft"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/draft/picks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pick */
        post: operations["ApiDraftPicksPick"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/draft/pool/abilities/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** RemoveAbility */
        delete: operations["ApiDraftPoolAbilitiesNameRemoveAbility"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/draft/pool/heroes/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** RemoveHero */
        delete: operations["ApiDraftPoolHeroesNameRemoveHero"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/draft/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset */
        post: operations["ApiDraftResetReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/draft/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** SetPreferences */
        post: operations["ApiDraftPreferencesSetPreferences"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/draft/undo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Undo */
        post: operations["ApiDraftUndoUndo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lookups/abilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Abilities */
        get: operations["ApiLookupsAbilitiesAbilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lookups/heroes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Heroes */
        get: operations["ApiLookupsHeroesHeroes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AbilityEntry */
        AbilityEntry: {
            id: number;
            name: string;
            is_ult: boolean;
        };
        /** AddAbilityBody */
        AddAbilityBody: {
            name: string;
            slot?: number | null;
            /** @enum {null|string} */
            kind?: "ult" | "basic" | null;
        };
        /** AddHeroBody */
        AddHeroBody: {
            name: string;
            slot?: number | null;
        };
        /** AnnotatedDraft */
        AnnotatedDraft: {
            player_picks: {
                [key: string]: components["schemas"]["AnnotatedPlayerPick"];
            };
            hero_pool_remaining: number[];
            basic_pool_remaining: number[];
            ult_pool_remaining: number[];
            hero_pool_all: (number | null)[];
            basic_pool_all: (number | null)[];
            ult_pool_all: (number | null)[];
            hero_pool_names: string[];
            basic_pool_names: string[];
            ult_pool_names: string[];
            hero_pool_all_names: (string | null)[];
            basic_pool_all_names: (string | null)[];
            ult_pool_all_names: (string | null)[];
            mmr: [
                number | null,
                number | null,
                number | null,
                number | null,
                number | null,
                number | null,
                number | null,
                number | null,
                number | null,
                number | null
            ];
            pick_slot: number;
            turn: number;
            hero_id?: number | null;
            draft_ability_id?: number | null;
            action_key: string;
            is_random: boolean;
            radiant_win: boolean;
            match_id: number;
            history: components["schemas"]["HistoryEvent"][];
        };
        /** AnnotatedPlayerPick */
        AnnotatedPlayerPick: {
            hero?: number | null;
            basics: number[];
            ult?: number | null;
            hero_name?: string | null;
            basics_names: string[];
            ult_name?: string | null;
        };
        /** ConfidenceInfo */
        ConfidenceInfo: {
            state_support?: number | null;
            /** @enum {null|string} */
            state_band?: "high" | "medium" | "low" | null;
        };
        /** DraftEnvelope */
        DraftEnvelope: {
            state: components["schemas"]["AnnotatedDraft"];
            suggestions: components["schemas"]["SuggestionEntry"][];
            confidence: components["schemas"]["ConfidenceInfo"];
            preferences?: components["schemas"]["PreferencesState"] | null;
            recommenders?: string[];
            /** @default bc */
            recommender: string;
            /** @default 1 */
            reweight_beta: number;
        };
        /** HeroEntry */
        HeroEntry: {
            id: number;
            name: string;
        };
        /** HistoryEvent */
        HistoryEvent: {
            hero_id?: number | null;
            draft_ability_id?: number | null;
            action_key: string;
            is_random: boolean;
            picker_disconnected: boolean;
        };
        /** PickBody */
        PickBody: {
            id: number;
            /** @enum {string} */
            type: "hero" | "basic" | "ult";
            /** @default false */
            is_random: boolean;
        };
        /** PreferencesState */
        PreferencesState: {
            preset: string;
            presets: components["schemas"]["PresetEntry"][];
            stat_names: string[];
            active_weights: number[];
            stat_norm_mean?: number[] | null;
            stat_norm_std?: number[] | null;
        };
        /** PresetEntry */
        PresetEntry: {
            name: string;
        };
        /** SetPreferencesBody */
        SetPreferencesBody: {
            preset?: string | null;
            recommender?: string | null;
            reweight_beta?: number | null;
        };
        /** SuggestionEntry */
        SuggestionEntry: {
            id: number;
            name: string;
            /** @enum {string} */
            type: "hero" | "basic" | "ult";
            prob: number;
            q?: number | null;
            q_vec?: number[] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ApiDraftPoolAbilitiesAddAbility: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddAbilityBody"];
            };
        };
        responses: {
            /** @description Document created, URL follows */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftEnvelope"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    ApiDraftPoolHeroesAddHero: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddHeroBody"];
            };
        };
        responses: {
            /** @description Document created, URL follows */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftEnvelope"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    ApiDraftGetDraft: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftEnvelope"];
                };
            };
        };
    };
    ApiDraftPicksPick: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PickBody"];
            };
        };
        responses: {
            /** @description Document created, URL follows */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftEnvelope"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    ApiDraftPoolAbilitiesNameRemoveAbility: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftEnvelope"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    ApiDraftPoolHeroesNameRemoveHero: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftEnvelope"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    ApiDraftResetReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Document created, URL follows */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftEnvelope"];
                };
            };
        };
    };
    ApiDraftPreferencesSetPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetPreferencesBody"];
            };
        };
        responses: {
            /** @description Document created, URL follows */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftEnvelope"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    ApiDraftUndoUndo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Document created, URL follows */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftEnvelope"];
                };
            };
        };
    };
    ApiLookupsAbilitiesAbilities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AbilityEntry"][];
                };
            };
        };
    };
    ApiLookupsHeroesHeroes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeroEntry"][];
                };
            };
        };
    };
}
